audio_model:
  pretrained: "m-a-p/MERT-v1-95M"
  local_path: "/beegfs/general/sa25abo/research_workplace/Models/huggingface_cache/m-a-p__MERT-v1-95M"
  freeze_backbone: true
  hidden_dim: 256
  transformer_layers: 2
  attention_heads: 4
  ffn_dim: 512
  dropout: 0.20
